### Python Numpy Arrays

- open source Python library
- provides ndarray, a homogeneous n-dimensional array object


**NumPy** is the primary scientific computing library in Python that adds support for fast and efficient handling of large multi-dimensional arrays (matrices).

The primary building block of NumPy is the `numpy.ndarray`, also known by and commonly referred to using the alias `numpy.array` or `np.array`. It is a homogeneous multi-dimensional (*n-dimensional*) array that is fixed in size. The numpy `np.array` differs from a regular Python `list` in three key ways:

1. All elements in a `np.array` must be the same datatype. (For example, only integers or only floating-point numbers, but never both.)
2. The datatype of an `np.array` or its elements cannot be changed in-place. To do so, a new array must be created and elements have to be copied over and re-cast into a different datatype.
2. The size of a `np.array` is fixed - new elements cannot be added nor can elements be removed. However, elements can be overwritten as long as you keep the same datatype.

*Note that Python also contains a type of array called `array.array` which supports only one dimension and hence is very different from the NumPy `np.array`.*

In [ ]:
import numpy as np     #  np is alias
# from numpy import *
# import numpy

In [ ]:
m = [
    [1,2,3.2,'2'],
    [4,5,6],
    [7,8,9]
  ]

In [ ]:
print(m)

In [ ]:
# Advantage of Numpy array over lists ?

In [ ]:
# Python list
print('1-D array')
lst = [1,2,3,4]
arr = np.array(lst)
arr

In [ ]:
arr[0]

In [ ]:
type(arr[0])

In [ ]:
type(arr)

In [ ]:
# Python list
print('1-D array')
# lst = [1,2,3,4.2]
arr = np.array([1,2,3,4.2])
arr

In [ ]:
arr[0]

In [ ]:
type(arr[0])

In [ ]:
type(arr)

In [ ]:
# Python list
print('1-D array')
lst = [1,2,3,'4.2']
arr = np.array(lst)
arr

In [ ]:
# Python list
print('1-D array')
lst = [1,2,3,('4',1)]
arr = np.array(lst)
arr

In [ ]:
# Python list
print('1-D array')
lst = [1,2,3,4]
arr = np.array(lst)
arr

In [ ]:
arr.shape

In [ ]:
print('2-D Array')
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

In [ ]:
lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [3,4,5,6,7]
arr1=np.array([[lst1,lst2,lst3],[lst1,lst2,lst3]])
arr1

In [ ]:
arr1[0][0][0]

In [ ]:
arr1.shape

In [ ]:
print('3-D array')
c = np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]])
print(c)

In [ ]:
c[0]

In [ ]:
b

In [ ]:
# size => tells about no. of elements in that array
print(arr.size)
print(b.size)
print(c.size)

In [ ]:
arr = np.array(lst)
b = np.array([[1,2,3,4],[5,6,7,8]])
c = np.array([[[1,2],[3,4],[5,6]]])

In [ ]:
print(c)

In [ ]:
arr

In [ ]:
b

In [ ]:
c

In [ ]:
# shape => (rows,columns)
print(arr.shape)
print(b.shape)
print(c.shape)

In [ ]:
c = np.array([[[1,2],[3,4],[5,6]]])  # try to add another element !

In [ ]:
print(c.shape)

In [ ]:
arr

In [ ]:
# dtype
print(arr.dtype)
print(b.dtype)
print(c.dtype)

In [ ]:
d = np.array([[1,2.2],
              [6,8.2],
               [10,11]])
print(d.dtype)

In [ ]:
print(d)

In [ ]:
d.shape

### Array Attributes

NumPy arrays have multiple useful attributes that give us information about the array. Here are some of the most common and useful ones.

- `.size` gives you the **number of elements** in the array
- `.shape` gives you the **dimensions** (size in each dimension) of the array
- `.ndim` gives you the **number of dimensions** (dimensionality) of the array
- `.dtype` gives you the **datatype** of the array

In [235]:
a = np.array([[[1, 2, 3, 4.1], [5, 6, 7, 8], [9, 10, 11, 12]],
              [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])
print(a)

[[[ 1.   2.   3.   4.1]
  [ 5.   6.   7.   8. ]
  [ 9.  10.  11.  12. ]]

 [[13.  14.  15.  16. ]
  [17.  18.  19.  20. ]
  [21.  22.  23.  24. ]]]


In [231]:
# number of elements
a.size

24

In [232]:
# dimensions
a.shape

(2, 3, 4)

In [233]:
# number of dimensions
a.ndim

3

In [236]:
# datatype
a.dtype

dtype('float64')

In [237]:
d = np.array([[1,2.2],
              [6,8.2],
               [10,11]])

In [238]:
print(d)

[[ 1.   2.2]
 [ 6.   8.2]
 [10.  11. ]]


In [239]:
# transpose
trans_d = d.transpose()

In [240]:
print(trans_d)

[[ 1.   6.  10. ]
 [ 2.2  8.2 11. ]]


In [242]:
# np.empty((rows,cols),dtype)
a = np.empty((4,4), dtype=int)

array([[98217929708153,              0,   489626271856,   481036337263],
       [  450971566194,   498216206433,   137438953573,   476741369961],
       [  498216206435,   137438953580,   476741369958,   137438953586],
       [  433791696996,   450971566198,   433791696995,              0]])

In [244]:
# np.ones((rows,cols),dtype)
x = np.ones(6,dtype=int)
x

array([1, 1, 1, 1, 1, 1])

In [245]:
y = np.ones((3,5))
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [246]:
z = np.ones((3,5), dtype = int)
z

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [247]:
# np.zeros((rows,cols), dtype)
x = np.zeros(4)
x

array([0., 0., 0., 0.])

In [248]:
y = np.zeros((3,2))
y

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [249]:
i = np.zeros((3,4), dtype=int)
i

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [250]:
z = np.ones ((4,8),dtype = bool)
z

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [251]:
z = np.zeros ((4,8),dtype = bool)
z

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [ ]:
z = np.ones ((4,8),dtype = str)
z

In [ ]:
z = np.zeros ((4,8),dtype = str)
z


- `np.full()` creates an array and sets all elements to a specified value

In [ ]:
np.zeros(3)

In [ ]:
np.ones(4)

In [ ]:
np.full(5, fill_value=7)

In NumPy, the "arange" function is used to create an array with evenly spaced values within a given range. The function is similar to the built-in Python range function, but it returns a NumPy array instead of a list. The basic syntax for using the "arange" function is as follows:

In [ ]:
# np.arange(start , end , step)

In [ ]:
a = np.arange(1,20) #by default step is 1
print(a)

In [ ]:
a = np.arange(1,20,2)
print(a)

In [ ]:
# to print even nos.
e = np.arange(2,20,2)
print(e)

In [ ]:
# odd nos.
o = np.arange(1,20,2)
print(o)

In [ ]:
# array.reshape((rows,cols))

In [ ]:
e

In [ ]:
e.reshape((3,3))

In [ ]:
e

In [ ]:
e = e.reshape((3,3))

In [ ]:
e

In [ ]:
e.flatten()

In [ ]:
e

In [ ]:
e = e.flatten()

In [ ]:
e

In [ ]:
# to print even nos.
e = np.arange(2,20,2)
e = e.reshape((3,3))
print(e)

#### flatten() :
-  Return copy of original array
- If you modify any value of this array, value of original array is not affected.
- Flatten is a method of an ndarray object.

While possible, it is not recommended to use `np.arange()` with **floating-point** numbers as is it difficult to predict the final number of elements. (This is due to the *somewhat imprecise* way floating-point numbers are stored in computer memory.) Hence, it is recommended you use `np.linspace()` when working with floating-point numbers. (Note that `np.linspace()` can also be used with integers.)

In [ ]:
np.linspace(0, np.pi, 20) # creates a NumPy array containing 20 evenly spaced values between the range 0 and π (inclusive)

In [ ]:
np.linspace(0, 40, 21)

In [ ]:
np.linspace(0, 40, 20)

There are other more niche constructors in NumPy. For example, you can use `np.eye()` to create a unit matrix.

In [ ]:
np.eye(5)

### Numpy array slicing operations

In [ ]:
a = np.arange(1,51)
a

In [ ]:
a = a.reshape(10,5)
a

In [ ]:
a[1]

In [ ]:
a[1,2]

In [ ]:
a[2:5]

In [ ]:
a

In [ ]:
a[0:9] # 9 exclu

In [ ]:
a[0:10]

In [ ]:
a[0:11]

In [ ]:
a[50]

In [ ]:
a

In [ ]:
a[:,2]

In [ ]:
a[2:5,4]

In [ ]:
a[:,:]

In [ ]:
a[:,2:5]

In [ ]:
a[:,:].dtype

In [ ]:
a = np.arange(0,18).reshape((6,3))
b = np.arange(20,38).reshape((6,3))
print('a : \n',a)
print('b : \n',b)

In [ ]:
np.add(a,b)

In [ ]:
a+b

In [ ]:
result = a + b

In [ ]:
result

In [ ]:
np.subtract(a,b)

In [ ]:
np.multiply(a,b)

In [ ]:
a*b

In [ ]:
a/b

In [ ]:
np.divide(a,b)

In [ ]:
a

In [ ]:
np.divide(b,a)

In [ ]:
a

In [ ]:
b

In [ ]:
# matrix multiplication
a@b

In [ ]:
# got an error because the shape for multiplication of matrices are not in the required form
print(a.shape)
print(b.shape)

In [ ]:
b = b.reshape((3,6))

In [ ]:
print(a.shape)
print(b.shape)

In [ ]:
a@b

In [ ]:
# a.dot(b) gives the same output as a@b
a.dot(b)

In [ ]:
b

In [ ]:
b.max()

In [ ]:
b.min()

In [ ]:
# b.max and b.min gives the max and min value of b whereas b.argmax gives the index of that max value
b.argmax()

In [ ]:
np.sum(b)

In [ ]:
b

In [ ]:
# axis=1 means row (lignes) and 0 means cols
# np.sum(b, axis=1) gives sum of every row
np.sum(b, axis=1)

In [ ]:
np.sum(b, axis=0)

In [ ]:
# square root of every element of b
np.sqrt(b)

In [ ]:
# np.std(b) gives the S.D. of b
np.std(b)

In [ ]:
# np.log(b) takes log of every element
np.log(b)

#### Trigonometric Operations

In [ ]:
np.pi

In [ ]:
np.sin(np.pi/2)

In [ ]:
np.sin(np.pi/4)

In [ ]:
np.cos(np.pi/6)

In [ ]:
np.cos(0)

In [ ]:
np.tan(np.pi/2)

### Random

In [ ]:
np.random.random(1)

In [ ]:
np.random.random(2)

In [ ]:
np.random.random((2,2))

In [ ]:
np.random.randint(1,10,(2,2))

In [ ]:
np.random.randint(1,10,(3,4,5))

In [ ]:
np.random.rand(2,2)

In [ ]:
# randn contains both positive and negative
np.random.randn(2,2)

In [ ]:
a = np.arange(1,10)
print(a)

In [ ]:
np.random.choice(a)

# Exercices

Create a 3x3 NumPy array filled with values from 1 to 9. Then, use slicing to extract the second row and the last column.

Create two 2D NumPy arrays of shape (2, 3) filled with random integers. Perform element-wise addition, multiplication, and subtraction between them.

Create a 2D NumPy array with 12 elements (e.g., a 3x4 array). Reshape it to a 4x3 matrix and then transpose the reshaped matrix

Create two arrays: one with shape (3, 1) and another with shape (1, 4). Perform element-wise addition using broadcasting.

Create a 5x5 NumPy array filled with random values between 0 and 1. Calculate the mean, standard deviation, and the sum of each row and each column.

Create a 3x3 NumPy array with random integers between 1 and 100. Find the maximum, minimum, and their respective indices along each axis.